// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJoV6JTMVYgbCwMaEVNPngK5i26LG3ixg',
    appId: '1:61138803492:web:15f7273a13047ec582b1b1',
    messagingSenderId: '61138803492',
    projectId: 'fir-modul-6-87fdf',
    authDomain: 'fir-modul-6-87fdf.firebaseapp.com',
    storageBucket: 'fir-modul-6-87fdf.firebasestorage.app',
    measurementId: 'G-MB7VYKXBNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAZhI3exlcEmK7KXwC0MAbS6RhkksV-4w',
    appId: '1:61138803492:android:1ff6a77cba17415182b1b1',
    messagingSenderId: '61138803492',
    projectId: 'fir-modul-6-87fdf',
    storageBucket: 'fir-modul-6-87fdf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcLShDApNuGqtVAftfGwm4F4Zpy2fj8Tw',
    appId: '1:61138803492:ios:3f51c414f131809982b1b1',
    messagingSenderId: '61138803492',
    projectId: 'fir-modul-6-87fdf',
    storageBucket: 'fir-modul-6-87fdf.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcLShDApNuGqtVAftfGwm4F4Zpy2fj8Tw',
    appId: '1:61138803492:ios:3f51c414f131809982b1b1',
    messagingSenderId: '61138803492',
    projectId: 'fir-modul-6-87fdf',
    storageBucket: 'fir-modul-6-87fdf.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJoV6JTMVYgbCwMaEVNPngK5i26LG3ixg',
    appId: '1:61138803492:web:c46e7ee7cab9d6b682b1b1',
    messagingSenderId: '61138803492',
    projectId: 'fir-modul-6-87fdf',
    authDomain: 'fir-modul-6-87fdf.firebaseapp.com',
    storageBucket: 'fir-modul-6-87fdf.firebasestorage.app',
    measurementId: 'G-T568M08ETR',
  );

}